spring.data.mongodb.uri=mongodb://diagana:diagana@localhost:27017/gestionemployer?authSource=admin
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=gestionemployer
spring.data.mongodb.username=diagana
spring.data.mongodb.password=diagana

server.port=9096

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


#spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/xe
#spring.datasource.username=diagana
#spring.datasource.password=diagana

#server.port=8081

#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

